name: quiz_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_provider: ^2.1.0
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  image_picker: ^1.0.4
  kartal: ^3.5.0
  flutter_svg: ^2.0.9
  dotted_line: ^3.2.2




dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Icons/AppIcon.png"
  adaptive_icon_foreground: "assets/Icons/AppIcon.png"



  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Icons/
    - assets/Lottie/